version: '3.9'
services:
  postgres-inventory:
    container_name: postgres-inventory
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory_service_v1
    ports:
      - "5434:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

  postgres-user:
    container_name: postgres-user
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user_service_v1
    ports:
      - "5436:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:14.9-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak_service_v1
    ports:
      - "5439:5432"
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    command:
      - "start-dev"
      - "--features=preview"
      - "--import-realm"
#      - "--features=token-exchange,declarative-user-profile"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak_service_v1
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: secret
      KC_DEBUG: true
      KC_DEBUG_PORT: "*:8787"
      KC_HTTP_PORT: 8090
      KC_HEALTH_ENABLED: true
      TZ: UTC
    ports:
      - "8090:8090"
      - "8787:8787"
    networks:
      - internal-network
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    volumes:
      - ./realms/:/opt/keycloak/data/import/

networks:
  internal-network:

volumes:
  postgres-keycloak-data:
  postgres-inventory-data:
  postgres-user-data:
#  postgres-product-data:
#  postgres-order-data:
#  postgres-payment-data:
#  activemq-data:
#  activemq-log:
#  cache: